import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-start justify-start p-24 font-mono space-y-5">
          <header>
            <div className="w-full items-start justify-start">
              <h1 className="text-lg">Intersog Code Challenge</h1>
            </div>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
