import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SigninForm } from "@/app/ui/signup-form";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col items-start justify-start p-24 font-mono space-y-5">
          <header
            className={"w-full flex flex-row items-start justify-between"}
          >
            <div className="">
              <h1 className="text-lg">
                <Link href={"/"}>Intersog Code Challenge</Link>
              </h1>
            </div>

            <div>
              <SigninForm />
            </div>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
